### ISSUE TITLE
scripts with similar names. ( naming conventions) 

### ISSUE THREAD

**Issue by danialabdl** [Godot-ground/tower-defense#5]
we have two different storm-troop.gd file in two seperate paths. i suggest changing one of them. for example storm_troop_class.

**Comment by blotterchains** [comment]
yes it's good idea.but please just rename it in our style code.
dont use undeline for separate that
storm-troops-class.gd
please see in this perspective.the root folders as root library and their subdirectories as components and subdirectories of these components as library.it's not a big deal we have same name but you are right we need to change that for better Developer Experience

**Comment by blotterchains** [comment]
it's better to dont break the style of the codes and file names.we need to make this for big scale projects.and maybe we can use this Core and files in other project as modular boilerplate
